name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop, release/* ]

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: false
jobs:
  build:
    name: Lint, Type-Check, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        continue-on-error: true
        run:
          # TODO store exit code of 'bun run lint' to Workflow variable to fail the workflow later
          bun run lint
      - name: Test
        run: bun run test -- --run

      - name: Type Check
        run: bun run typecheck

      - name: Build
        run: bun run build

      - name: Link local package
        run: bun link

      - name: Demo - Install dependencies
        working-directory: example
        run: |
          bun uninstall vite-plugin-vue-i18n-typescript
          bun install
          bun link vite-plugin-vue-i18n-typescript

      - name: Demo - Build
        working-directory: example
        run: bun run build-only

      - name: Demo - Lint
        working-directory: example
        run: bun run lint

      - name: Demo - Type Check
        working-directory: example
        run: bun run typecheck

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/heads/main/')
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload built demo site
          path: example/dist

      - name: Deploy to GitHub Pages
        if: startsWith(github.ref, 'refs/heads/main/')
        id: deployment
        uses: actions/deploy-pages@v4




